README.md
This PR adds an initial README.md describing the basic setup process and handling of this repository.
See [this](https://github.com/UHHRobotics22-23/robot_project/tree/docs/initial_readme) for a rendered preview.
=> Add an initial README.md

marimbabot_vision/scripts/generate_data.py
remove footer in data generation
=> remove lilypond footer line

marimbabot_vision/scripts/train.py
The training script is now able to concatenate a selection of train or validation datasets on the fly. This helps us when training with e.g. handwritten, real-world and augmented samples at once.
The PR also includes these minor changes:
- Auto-rotate images from landscape to portrait
- Add model names to the config
- Reduce the number of training epochs
- Add a progress bar for the dataset initialization
=> Allow training on multiple datasets

.gitignore, marimbabot_vision/scripts/detect.py, marimbabot_vision/scripts/generate_hw_data.py
- Add detection script to run a given model on a sample image
- Support model and dataset versions in gitignore
- Fix deprecation warning and slow execution on highly parallel machines (hand written data generation) (a bit off topic sry)
=> Add detection script for the transformer model

.gitignore, marimbabot_vision/scripts/detect.py, marimbabot_vision/scripts/generate_augmented_data.py, marimbabot_vision/scripts/generate_data.py, marimbabot_vision/scripts/generate_dataset_full.sh, marimbabot_vision/scripts/generate_hw_data.py, marimbabot_vision/scripts/real_world_data_collection.py, marimbabot_vision/scripts/train.py, requirements.txt
manage data generation
wait for https://github.com/UHHRobotics22-23/robot_project/pull/8 to be merged
=> data generation configuration 

marimbabot_vision/scripts/detect.py, marimbabot_vision/scripts/generate_data.py, marimbabot_vision/scripts/generate_hw_data.py, marimbabot_vision/scripts/train.py
Some fixes regarding whitespace issues in the network output.
=> Fix tokenization

requirements.txt
that should be the correct version as it is from the computer we tested on
@Flova
=> add open_cv_version

marimbabot_vision/scripts/flatten_whiteboard_data.py
Takes a data set with multiple whiteboard images per sample (as generated from real_world_data_collection.py) and creates a separate data set in the typical structure with just one image per sample.
Sample names consist of sample number (from input data set) and whiteboard image number (from input data set sample) connected with '_'.
Deletion of whiteboard images in input data set is disabled to not interfere with real_world_data_collection.py until whiteboard data collection is finished.
=> script for whiteboard data outsourcing

README.md, marimbabot_vision/scripts/flatten_whiteboard_data.py, requirements.txt
=> add launch info

marimbabot_vision/config/cv_camera.yaml, marimbabot_vision/config/vision_node.yaml, marimbabot_vision/launch/marimbabot.launch
I guess that is faster than you expected 😆  @Flova
=> add separate config

marimbabot_vision/CMakeLists.txt, marimbabot_vision/launch/marimbabot.launch, marimbabot_vision/package.xml, marimbabot_vision/src/vision_node.py, marimbabot_vision/src/visualization_node.py
opens a visualization of the notes recognized by the vision node
=> add lilypond visualization

marimbabot_vision/config/vision_node.yaml, marimbabot_vision/package.xml, marimbabot_vision/src/vision_node.py
The model is now available of the Huggingface Hub: https://huggingface.co/Flova/omr_transformer
This allows us to distribute the model for free and share it with other people (it even features an automated web UI and API).
=> Use huggingface hub for model distribution

marimbabot_vision/scripts/detect.py, marimbabot_vision/scripts/train.py, marimbabot_vision/src/vision_node.py
Add latest training config. Also simplify explicit image alignment using buildin huggingface feature.
The latest model can be seen on https://huggingface.co/Flova/omr_transformer
=> Add setup from the latest trainig run

README.md
=> add lilypond to installation

requirements.txt
fixes err during inference time when using the remote model weights configuration
=> upgrade transformers version

README.md, marimbabot_vision/package.xml
use the dependency as it was merged here https://github.com/ros/rosdistro/pull/36561
=> add lilypond as rosdep

marimbabot_vision/src/vision_node.py
=> add queue size to recognized_notes

README.md, marimbabot_hardware/config/joint_limits.yaml, marimbabot_hardware/src/servo_interface.cpp, marimbabot_hardware/urdf/two_mallet_holder.urdf
=> Adjusted hardware limits as the servo is only able to cover 180°

marimbabot_description/launch/marimbabot_ur5_upload.launch, marimbabot_ur5_moveit_config/launch/marimbabot_gazebo.launch
Automatically choose prismatic joints for gazebo simulation
=> Add prismatic bar joints for simulation

marimbabot_speech/CMakeLists.txt, marimbabot_speech/package.xml, marimbabot_speech/src/speech_synthesis.py
small changes to the synthesis node
=> Fix synthesis node

marimbabot_behavior/src/marimbabot_behavior/behavior_node.py
@yunlong-wang-cn would be cool if you could test it for me :)
=> include command message

marimbabot_audio/scripts/dummy_client_audio_from_lilypond.py, marimbabot_audio/src/audio_from_lilypond.py, marimbabot_behavior/src/marimbabot_behavior/behavior_node.py, marimbabot_msgs/CMakeLists.txt, marimbabot_msgs/action/LilypondAudio.action
I removed the node that listens to the vision node by default.
I changed it so it is an action and may fit better with our behavior.
Please let me know if that fits for you, I also implemented something inside the behavior files fyi @scaredycode .
=> lilypond to audio behavior integration

marimbabot_audio/package.xml, marimbabot_speech/package.xml
fix bug from #160
@scaredycode please check it. 
Or you can try to use `rosdep install --from-paths src --ignore-src -r -y` to install the dependecies.
=> fix package.xml

marimbabot_behavior/src/marimbabot_behavior/interpreter.py
I guess this is just an artifact of some debugging
=> rm unnecessary loc

marimbabot_behavior/src/marimbabot_behavior/behavior_node.py, marimbabot_msgs/msg/HitSequenceElementList.msg
this message type contains a list of HitSequenceElement
@yunlong-wang-cn We should talk about whether this fits you (receiving a list of notes all the time) or if you prefer to receive a single note per "publish".
=> forward message of planned hit sequences to topic audio/hit_sequence

marimbabot_vision/scripts/README.md, marimbabot_vision/scripts/generate_data.py
This PR fixes the dotted note problem (too many clocks in a bar)
simplifies the data that is generated by default
Adds a rotation to the output image, so this and the handwritten data are in portrait mode. (make generation a bit slower because it adds an extra read and write step)
=> 211 adjust the synthetic dataset generation

marimbabot_audio/launch/marimbabot.launch, marimbabot_audio/launch/marimbabot_rviz.launch, marimbabot_behavior/src/marimbabot_behavior/behavior_node.py, marimbabot_planning/README.md, marimbabot_speech/src/speech2text.py
- fix audio launch file for device value
- modify prompt message for speech
- add robot motion planning instructions with details for team members in planning folder
- set upper and lower bounds for tempo
=> Marimba integration test v2

marimbabot_msgs/msg/Command.msg, marimbabot_speech/src/text2command.py
change the msg-type of Command.msg
=> remove json usage for clearity

marimbabot_ur5_flex_double_moveit_config/config/fake_controllers.yaml, marimbabot_ur5_flex_double_moveit_config/config/marimbabot_ur5.srdf, marimbabot_ur5_moveit_config/config/fake_controllers.yaml
- updated initial pose for demo.launch to avoid collision
=> Fix double mallet start point collision

marimbabot_audio/launch/audio_feedback.launch, marimbabot_audio/script/peak_loudness.py, marimbabot_audio/src/eval_visualization.py, marimbabot_audio/src/onset_detection.py, marimbabot_planning/src/planning.cpp, marimbabot_speech/launch/command_recognition.launch, marimbabot_vision/config/cv_camera.yaml
=> Current demo config

marimbabot_vision/scripts/eval.py, marimbabot_vision/scripts/train.py
Add a script that evaluates a given model on a given dataset outside of the training
=> Add vision evaluation script

marimbabot_planning/README.md
=> motion planning readme
